### ISSUE TITLE
Command Line Arguments Checklist

### ISSUE THREAD

**Issue by roberthawdon** [roberthawdon/dfshow#15]
The following is a list of arguments DF-SHOW should accept:

*LS arguments:*
- [ ] ` -a, --all` - do not ignore entries starting with . (currently achievable with the `h` key)
- [ ] `-A, --almost-all` - as DF-SHOW must show `.` and `..` for navigation purposes, this will do the same as the above.
- [ ] `--author` - will add the author of the file to the `-Owner & Group-` section
- [ ] `-B, --ignore-backups` - do not list implied entries ending with ~
- [ ] `-f` - do not sort
- [ ] `-g` - only show group
- [ ] `-G, --no-group` - do not show group
- [ ] `-h, --human-readable` - print sizes like 1K 234M 2G etc.
- [ ] `--si` - use powers of 1000 not 1024
- [ ] `-r, --reverse` - reverse order while sorting
- [ ] `-S` - sort by file size, largest first
- [ ] `-t` - sort by modification time, newset first

*DF-SHOW arguments:*
- [ ] `--no-colors` - Disables colors in directory listing
- [ ] `--monochrome` - Disables all colors for monochrome output
- [ ] `--pager` - Set pager for single session
- [ ] `--editor` - Set editor for single session
